#!/bin/sh

HOME=$PWD
BUILDROOT_PATH=../../buildroot
DL_PATH=$BUILDROOT_PATH/dl
PROG_PATH=modul-src

####
#
#	TODO: 	->	refactor (maybe a list and a loop)
#			->	add entry "package/sys/Config.in" for package to 
#				"buildroot/package/Config.in" (e.g. sed '1i)
####


################ make template archive -> START


APP_NAME=template
VERSION=1.0
ARCHIVE_NAME=$APP_NAME-$VERSION

cd $HOME && cd $APP_NAME && make clean
cd $HOME && tar -cvzf $ARCHIVE_NAME.tar.gz $APP_NAME

# copy package to d1
cd $HOME && cp $ARCHIVE_NAME.tar.gz $DL_PATH/$ARCHIVE_NAME.tar.gz

cd $HOME && rm -fr $ARCHIVE_NAME
cd $HOME && rm -fr $ARCHIVE_NAME.tar.gz

cd $HOME

################ make template archive -> END

################ make openclose archive -> START

APP_NAME=openclose
VERSION=1.0
ARCHIVE_NAME=$APP_NAME-$VERSION

cd $HOME && cd $APP_NAME && make clean
cd $HOME && tar -cvzf $ARCHIVE_NAME.tar.gz $APP_NAME

# copy package to d1
cd $HOME && cp $ARCHIVE_NAME.tar.gz $DL_PATH/$ARCHIVE_NAME.tar.gz

cd $HOME && rm -fr $ARCHIVE_NAME
cd $HOME && rm -fr $ARCHIVE_NAME.tar.gz

cd $HOME

################ make openclose archive -> END


################ make zero archive -> START

APP_NAME=zero
VERSION=1.0
ARCHIVE_NAME=$APP_NAME-$VERSION

cd $HOME && cd $APP_NAME && make clean
cd $HOME && tar -cvzf $ARCHIVE_NAME.tar.gz $APP_NAME

# copy package to d1
cd $HOME && cp $ARCHIVE_NAME.tar.gz $DL_PATH/$ARCHIVE_NAME.tar.gz

cd $HOME && rm -fr $ARCHIVE_NAME
cd $HOME && rm -fr $ARCHIVE_NAME.tar.gz

cd $HOME

################ make zero archive -> END


echo "...done!"


