#!/bin/bash

##########################################
#### download & extract linux kernel #####
##########################################

home=$HOME'/system86/'

# remove old folder
rmdir $home

# create systemx86 folder
mkdir $home -p

# copy files and navigate to folder
cp -rf files/ $home
cd $home

# download linux kernel
wget https://www.kernel.org/pub/linux/kernel/v3.x/linux-3.16.6.tar.xz

# extract package
tar xpvf linux-3.16.6.tar.xz

#initialize
mkdir initramfs/
gcc --static -m32 files/systeminfo.c -o systeminfo

mv systeminfo initramfs/systeminfo
mv files/init.sh initramfs/
mv files/busybox initramfs/

##########################################
#### linux kernel configuration      #####
##########################################

# compile kernel
cd linux-3.16.6/
make clean
mv ../files/.config .config
ARCH=i386 make -j4  

# clean up
cd ..
rm -f linux-3.16.6.tar.xz
rm -rf initramfs/
rm -rf files/

#run kernel
qemu -kernel arch/x86/boot/bzImage



