#!/bin/bash

# REQUIRED folder structure:
#
# /linux
# /busybox
# /[folderXY]/v2arm
# /[folderXY]/initramfs/
#

# versions
LINUX_VERSION=linux-3.16.6
BUSYBOX_VERSION=busybox-1.22.1

# cross compiler
CROSS_COMPILER=/group/labworks/toolchain/buildroot.git/output/host/usr/bin/arm-buildroot-linux-uclibcgnueabihf-

# kernel architecture
ARCH=arm

# paths
KERNEL_PATH=../$LINUX_VERSION
BUSYBOX_PATH=../$BUSYBOX_VERSION
INITRAMFS_PATH=initramfs
IMAGE_PATH="arch/arm/boot/zImage"

# --------
LINUX_PACKAGE=$LINUX_VERSION.tar.xz
LINUX_SOURCE=https://www.kernel.org/pub/linux/kernel/v3.x/$LINUX_PACKAGE
BUSYBOX_PACKAGE=$BUSYBOX_VERSION.tar.bz2
BUSYBOX_SOURCE=http://busybox.net/downloads/$BUSYBOX_PACKAGE
################# tools #################
comile_app()
{
	$CROSS_COMPILERgcc -static -o start systeminfo.c 
	mv start $INITRAMFS_PATH/bin/start
}


################# initrd ################
initrd()
{
	cd $BUSYBOX_PATH && make ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILER install
	cd $BUSYBOX_PATH && mkdir dev proc sys tmp lib
	
	# copy needed files in rootfs
	cp -r $INITRAMFS_PATH/etc $BUSYBOX_PATH/_install/etc
	cp $INITRAMFS_PATH/bin/start $BUSYBOX_PATH/_install/bin/start
	
	# set permission
	chmod +x $BUSYBOX_PATH/_install/etc/init.d/rcS
	chmod +x $BUSYBOX_PATH/_install/bin/start
	
	## copy start script und files for udhcpc
	cp -f $INITRAMFS_PATH/bin/startServer $BUSYBOX_PATH/_install/usr/bin/startServer
	cd $BUSYBOX_PATH/_install/usr/bin && chmod +x startServer
	cp -r scripts/udhcp $(BUSYBOX_PATH)/_install/etc/udhcpc

	# create image
	cd $BUSYBOX_PATH/_install && find . | cpio -o --format=newc > ../../rootfs.img

}

################# KERNEL ##################
menu_kernel()
{
	cd $KERNEL_PATH && make ARCH=$ARCH menuconfig
}

compile_kernel()
{
	cd $KERNEL_PATH && make ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILER -j4
}

defconfig_kernel()
{
	cd $KERNEL_PATH &&  make ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILER vexpress_defconfig
}


################# BUSYBOX ##################

defconfig_busybox()
{
	cd $BUSYBOX_PATH && make ARCH=$ARCHdefconfig
}

menu_busybox()
{
	cd $BUSYBOX_PATH && make ARCH=$ARCH menuconfig
}

#################### QEMU ##################
qemu_start()
{
	cd $KERNEL_PATH &&  QEMU_AUDIO_DRV=none qemu-system-arm -initrd ../rootfs.img -kernel $IMAGE_PATH -M vexpress-a9 \
	-nographic -append "rdinit=/sbin/init console=ttyAMA0" 
}

qemu_net()
{
	cd $KERNEL_PATH && QEMU_AUDIO_DRV=none qemu-system-arm -kernel $IMAGE_PATH -M vexpress-a9 \
	-nographic -initrd ../rootfs.img -append "rdinit=/sbin/init console=ttyAMA0" \
	-net nic,model=lan9118, macaddr=00:00:00:00:00:A5 \
	-net vde,sock="/tmp/vde2-tab0.ct1"
}


################## SOURCE ###############
source()
{
	cd ..
	# linux source
	wget $LINUX_SOURCE
	tar xpvf $LINUX_PACKAGE
	rm -f $LINUX_PACKAGE
	
	# busybox source
	wget $BUSYBOX_SOURCE
	tar xpvf $BUSYBOX_PACKAGE
	rm -f $BUSYBOX_PACKAGE
}



################## HELP ######################
help()
{
	echo "--------------------------------------------------------"
	echo "usage:"
	echo "./v2arm -e [function]"
	echo ""
	echo "functions:"
	echo ".....source:		download linux source"
	echo ".....defconfig_kernel: 	creates a default kernel config"
	echo ".....defconfig_busybox: 	creates a default busybox config"
	echo ".....compile_kernel:		complie kernel"
	echo ".....qemu_start:	starts qemu with compiled kernel"
	echo "--------------------------------------------------------"
	
}

while getopts ":e:h" opt; do
		case $opt in
			e)
				cmd=$OPTARG
				;;
			h)	
				help
				;;
			:)
				echo "missing argument"
				;;
			?)
				help
				;;
			*)
				echo "not yet implemented"
				help
				;;
		esac
done

$cmd

