#!/bin/sh 

# Say Hello
echo '######################'
echo 'Starting system'
echo '######################'

echo 0 > /proc/sys/kernel/printk

#start init program and display system infos
echo ''
echo '---> start binary'
./usr/bin/systeminfo

#sleep 2

# start server
echo '----> Starting Server'
ifconfig lo up
ifconfig eth0 up

udhcpc -s /etc/udhcpc/simple.script
ifconfig lo 127.0.0.1
route add -host 127.0.0.1 lo
httpd -h /www/ &
