#!/bin/sh

HOME=$PWD
BUILDROOT_PATH=../../buildroot
PACKAGE_PATH=$BUILDROOT_PATH/package
DL_PATH=$BUILDROOT_PATH/dl
PROG_PATH=../prog
APP_NAME=rugoapp
VERSION=1.0
ARCHIVE_NAME=$APP_NAME-$VERSION


# copy program folder to buildroot package..
cp -rf rugoapp $PACKAGE_PATH/rugoapp

# make archive
cd $HOME/$PROG_PATH

mkdir $ARCHIVE_NAME 
cd $HOME/$PROG_PATH && cp led5.c $ARCHIVE_NAME/led5.c
cd $HOME/$PROG_PATH && cp switch.c $ARCHIVE_NAME/switch.c
cd $HOME/$PROG_PATH && cp gpio.c $ARCHIVE_NAME/gpio.c
cd $HOME/$PROG_PATH && cp Makefile $ARCHIVE_NAME/Makefile
cd $HOME/$PROG_PATH && tar -cvzf $ARCHIVE_NAME.tar.gz $ARCHIVE_NAME
cd $HOME/$PROG_PATH && rm -fr $ARCHIVE_NAME

# copy package to d1
cd $HOME/$PROG_PATH && cp $ARCHIVE_NAME.tar.gz $DL_PATCH/$ARCHIVE_NAME.tar.gz

# insert package to config
cd $PACKAGE_PATH  && sed '951i	 source "package/rugoapp/Config.in"' Config.in

cd $HOME


